# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
