# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_auto_20170830_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
