# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_auto_20170830_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregation',
            name='user',
        ),
        migrations.AddField(
            model_name='aggregation',
            name='datetime',
            field=models.CharField(default=1.4, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aggregation',
            name='average',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aggregation',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='consumption',
            field=models.FloatField(),
        ),
    ]
