# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_auto_20170830_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregation',
            name='datetime',
        ),
        migrations.AddField(
            model_name='aggregation',
            name='date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumption',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
