# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0005_auto_20170830_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
